### ISSUE TITLE
the cutscenes where you destroy the castle seem to be messed up

### ISSUE THREAD

**Issue by danielh05** [VitorVilela7/wide-snes#1]
![image](https://user-images.githubusercontent.com/35849198/122609946-1d8aed00-d07f-11eb-9e29-eb693b092121.png)

**Comment by VitorVilela7** [comment]
Hi, thank you for the quick issue! I have fixed the issue, can you redownload the patch and try again?

**Comment by danielh05** [comment]
issue seems to be fixed! thank you so much!
