### ISSUE TITLE
(fixed)

### ISSUE THREAD

**Issue by NZgamer2008** [VitorVilela7/wide-snes#15]
[image](https://drive.google.com/file/d/1udf6PrFkev39k8NhbKZj2L4USCayG6u8/view?usp=sharing)

**Comment by VitorVilela7** [comment]
This happens when you use the "16:9" configuration directly from the emulator, without loading the BSO file. Once loading the BSO file, make sure to set scaling option to "scale" or "stretch" and enter full screen.

**Comment by NZgamer2008** [comment]
oh thanks
