### ISSUE TITLE
This happens..?

### ISSUE THREAD

**Issue by mikethecat** [VitorVilela7/wide-snes#17]
https://cdn.discordapp.com/attachments/856273023480627200/856629932066471956/unknown.png

I've probably got something wrong in the settings

**Comment by mikethecat** [comment]
https://cdn.discordapp.com/attachments/856273023480627200/856630600722939914/unknown.png 

This too

**Comment by VitorVilela7** [comment]
When this happens it means that it didn't load the BSO file.

1) Is the BSO file on the same folder as the ROM (SMC or SFC) file? It must stay in the same folder to work.
2) Does the BSO file has the same name as the ROM (SMC or SFC) file? It must have the same name as the ROM to work.
3) Are you using the latest bsnes_hd core? Latest version is beta 06

**Comment by tobinP** [comment]
Widescreen wasn't working for me until I saw your comment saying that the BSO file has to be in the same directory as the rom.  Might be worth adding that line to the instructions in the readme.

It's awesome now that it works!

**Comment by mikethecat** [comment]
> When this happens it means that it didn't load the BSO file.
> 
> 1. Is the BSO file on the same folder as the ROM (SMC or SFC) file? It must stay in the same folder to work.
> 2. Does the BSO file has the same name as the ROM (SMC or SFC) file? It must have the same name as the ROM to work.
> 3. Are you using the latest bsnes_hd core? Latest version is beta 06

Oh, I had completely forgotten I needed to add the BSO file. Thanks!
