### ISSUE TITLE
SA-1 Pack compatibility

### ISSUE THREAD

**Issue by boomshroom** [VitorVilela7/wide-snes#18]
From what I can tell, this pack was made the be at least partly compatible with the SA-1 Pack. While it appears to work mostly fine, there are a few areas where the two patches are currently incompatible. These largely concern borders, namely the title screen and overworld, which show areas beyond what would normally be seen, but have the original borders that don't extend to the edges. The other minor bug I've seen is upon entering a level and not having the screen pre-scrolled, so the level just stops at the left side of the usual area.

![Super Mario World HD-210621-133723](https://user-images.githubusercontent.com/628488/122825438-c8292880-d296-11eb-8be3-7aea8ec4ea4e.png)
![Super Mario World HD-210621-133734](https://user-images.githubusercontent.com/628488/122825442-c8c1bf00-d296-11eb-8879-dc1b8d7e8b43.png)
![Super Mario World HD-210621-133819](https://user-images.githubusercontent.com/628488/122825444-c95a5580-d296-11eb-8f74-5bd6f2f40e47.png)

So far, I haven't found any obvious places in the code that causes these, so it likely just has something to do with the different rendering system. I should mention that these issues do not appear when applying the widescreen patch to a fresh ROM. Gameplay appears to be unaffected outside of the level start.

**Comment by VitorVilela7** [comment]
SMW Widescreen (BPS patch) already comes with SA-1Pack v1.41 Low Power version (https://github.com/VitorVilela7/SA1-Pack/tree/low-power) applied together

**Comment by boomshroom** [comment]
Ah. Thank you!

I was mostly going by the comment `; WARNING: only works with vanilla SMW or vanilla SMW + SA-1 Pack` along with the code included to check if SA-1 was already applied.
