### ISSUE TITLE
[spam?] 3... 2... 1... Takedown

### ISSUE THREAD

**Issue by marcussacana** [VitorVilela7/wide-snes#21]
Cool man, good job, but it's a nintendo game... and... let's see what happen.

**Comment by TheLX5** [comment]
By not distributing actual ROM files and copyrighted code, the chances of this happening are much smaller than people think they are. Patches fairly good way (small & not illegal) to distribute mods, this is also why the ROM image for SMW isn't provided by Vitor.

**Comment by marcussacana** [comment]
Let's hope...

**Comment by jason-oliveira** [comment]
If a patch was grounds for a valid legal claim, Larry Wall would've been sued to death by 1988 for writing patch(1) to enable all these would-be pirates sharing Unix source code.

Requesting bug be closed for trollpost.
