### ISSUE TITLE
An option to disable in-game music?

### ISSUE THREAD

**Issue by TotiB** [VitorVilela7/wide-snes#23]
Cheat codes for vanilla Mario World, and another no-music patch I tried don't seem to work out with the widescreen hack. 
Could a cheat code, or an additional patch be made that can disable music?

**Comment by VitorVilela7** [comment]
Most cheat codes can be converted using the following rule:

7E00XXYY → 0030XXYY

7EZZXXYY → 40ZZXXYY
(only if ZZ is not 00)

Example 1:
7E001902 → 00301902

Example 2:
7E0DB301 → 400DB301

**Comment by TotiB** [comment]
Turns out the code I found that disabled music had a thing with it where Mario would flash star colors for some reason.
However, I did find [this ASM patch that mutes music](https://www.smwcentral.net/?p=section&a=details&id=4342) and it works with the widescreen hack, so it was exactly what I was looking for. 
The info about cheats is interesting though, definitely going to be using that second code you put!
