### ISSUE TITLE
Some sprites moving right while they should be moving left, at the beginning of a level sub-area

### ISSUE THREAD

**Issue by sken130** [VitorVilela7/wide-snes#26]
So far, I have found this problem in Vanilla Ghost House. I may find more instances of this issue as I play more.

![Instance 1 in Vanilla Ghost House](https://user-images.githubusercontent.com/7981861/123503814-f0929780-d687-11eb-977d-d997c7c6f322.png)
![Instance 2 in Vanilla Ghost House](https://user-images.githubusercontent.com/7981861/123503816-f1c3c480-d687-11eb-842a-ee0601ba01a1.png)
![Vanilla Ghost House Map overworld](https://user-images.githubusercontent.com/7981861/123503817-f1c3c480-d687-11eb-9015-6b822e94c861.png)

**Comment by TheLX5** [comment]
Same root issue as #13, possible fix in one of the comments.

**Comment by sken130** [comment]
Oh, then let's trace in #13 instead.
As for ASM patches, I think these should be applied by the ROM hack's author.
