### ISSUE TITLE
Compatibility with SA-1 Pack

### ISSUE THREAD

**Issue by RavenMacDaddy** [VitorVilela7/wide-snes#28]
Hello

Are there any plans to make the SA-1 pack and Widescreen patch compatible with each other? 

Cheers

**Comment by TheLX5** [comment]
The widescreen patch already uses SA-1 Pack, it uses a special branch called [low power](https://github.com/VitorVilela7/SA1-Pack/tree/low-power), as it tries to consume less electricity/resources by turning off the SA-1 chip when it's not being used, helps both emulators and real hardware.

**Comment by RavenMacDaddy** [comment]
Oh, that's awesome, thanks for the info!
