### ISSUE TITLE
Still black screen when launching in retroarch.

### ISSUE THREAD

**Issue by TAKfsg** [VitorVilela7/wide-snes#29]
When I launch the game on retroarch the game gets stuck on a black screen but I think this is my part so can someone help me?

**Comment by VitorVilela7** [comment]
Does booting regular SNES games lead to black screen too?

**Comment by TAKfsg** [comment]
> Does booting regular SNES games lead to black screen too?

yeah... im starting to think maybe this is a me problem then.

**Comment by TheGershon** [comment]
I'm seconding this. I'm using the correct SMW rom, a matching filename for the .bso file, and the latest versions of both RetroArch and the bsnes-HD-beta core. Other games work fine, it's just the SMW wide patch. I've tried patching with both FLIPS and RomPatcher.js.


![](https://i.imgur.com/vWLM2gs.png)

**Comment by VitorVilela7** [comment]
Just a heads up, are you all still having issues with Retroarch?

**Comment by TheGershon** [comment]
Just checked with the latest patch, latest retroarch, & latest bsnes-hd core and nope, no black screen.
![fdsa](https://user-images.githubusercontent.com/6880780/174514971-564cbafc-cc84-4021-a3e1-ce09717d0d8d.png)
Looks like something at some point fixed it, unless I'm just incredibly lucky.

**Comment by VitorVilela7** [comment]
Since I believe there is no issues about black screen on the latest version, I'm closing this issue. Let me know if you still have any issues.
