### ISSUE TITLE
world 2 castle - boss room walls never come down, leading to softlock

### ISSUE THREAD

**Issue by danielh05** [VitorVilela7/wide-snes#3]
https://user-images.githubusercontent.com/35849198/122612190-00581d80-d083-11eb-8cc0-f2ce0c78c30b.mp4

**Comment by VitorVilela7** [comment]
Hi! Thank you for the bug report! Another mistake done by me earlier morning while working on Ludwig. I have submitted the 1.2 patch correction, can you verify if it has been fixed?

**Comment by danielh05** [comment]
alright works now, thank you!
