### ISSUE TITLE
bso override files have no effect in RetroArch

### ISSUE THREAD

**Issue by VideogameScrapbook** [VitorVilela7/wide-snes#31]
I cannot get bso override files to work. I've tried several different ones on one ROM file as a test but they all have same result. Here is one example.

Steps to reproduce:
1. Download [smw-widescreen-v110.zip](https://github.com/VitorVilela7/wide-snes/releases/download/v1.10/smw-widescreen-v110.zip).
2. Unzip smw-widescreen-v110.zip.
3. Patch "Super Mario World (USA).sfc" (MD5: cdd3c8c37322978ca8669b34bc89c804) with smw-extrawide-par-v110.bps and save output as "SMW.sfc".
4. Delete smw-extrawide-par-v110.bps
5. Rename smw-extrawide-par-v110.bso to SMW.bso.
6. Delete bsnes-hd cfg and opt files.
7. Open retroarch 1.9.1.
8. Load core "bsnes-hd beta 10.6"
9. Open SMW.sfc.
10. Open core Options with Retroarch's quick menu.

Expected result:
The core Options should be overriden by the parameters in the bso file.

Actual result:
The default core options are used. I have to manually figure out equivalents in core options to match the bso overrides.

Related ticket in bsnes-hd beta repo:
https://github.com/DerKoun/bsnes-hd/issues/89

**Comment by jason-oliveira** [comment]
Does it work in RetroArch/bsnes-hd if you _don't_ patch the rom, and just leave the bps and bso files (named SMW.*) in the same directory?

**Comment by VideogameScrapbook** [comment]
The "Actual result" is still the same as described. The bps patch seems to work successfully still (widescreen wooden border still works on the title screen even though the file wasn't patched manually) but the BSO config file has no effect on the bsnes-hd core settings.

**Comment by 1XxEPICDJxX1** [comment]
any luck yet?

**Comment by VitorVilela7** [comment]
I believe the most recent documentation and release instructions should make it more clear how to set up widescreen SMW. Please let me know if you still have issues.
