### ISSUE TITLE
Possible to combine with SA-1 patch?

### ISSUE THREAD

**Issue by sofakng** [VitorVilela7/wide-snes#39]
Is it possible to patch SMW with both the widescreen and SA-1 patches?

**Comment by VitorVilela7** [comment]
The Super Mario World Widescreen already comes with SA-1 Pack (v1.41) included, is it the patch you are referring to?

**Comment by sofakng** [comment]
Yes.  I wasn't sure if it included the SA-1 (speedup) patches.  Thanks for the information!

**Comment by VitorVilela7** [comment]
Excellent, the patch is already integrated with widescreen, so no further action is required for playing with SA-1.
