### ISSUE TITLE
Feature request - Add support for Snes9x

### ISSUE THREAD

**Issue by update-freak** [VitorVilela7/wide-snes#41]
Hi,

it would be great if you could add support for Snes9x that this game could be playes on Kodi (LibreELEC) on RPi 3 with Xbox-360-Controller. For me bsnes does not run smoothly. Thanks

**Comment by VitorVilela7** [comment]
Snes9x support needs to be done on the [emulator side](https://github.com/snes9xgit/snes9x), because Widescreen is not a feature that includes with the original hardware, so it's up to the emulators add proper support for it.
