### ISSUE TITLE
Where's the release zip for v1.11?

### ISSUE THREAD

**Issue by Starman99x** [VitorVilela7/wide-snes#42]
Hi, you forgot to add the zip file that should contain all different options for patch v1.11.

![orca-image--885275672](https://user-images.githubusercontent.com/69786862/194334652-2a18bf64-2a83-4140-8b54-1de9bc964553.jpeg)

**Comment by SamRetro** [comment]
I didn't know the Source code (zip) had everything.

**Comment by Starman99x** [comment]
I thought the source code zip had all the .bps files but it didn't.

**Comment by VitorVilela7** [comment]
Hello! Sorry about this, I just included the binaries into the [release](https://github.com/VitorVilela7/wide-snes/releases/tag/v1.11). Please try again.

**Comment by VitorVilela7** [comment]
Please reopen this issue if you're still having difficult with setting up widescreen.
