### ISSUE TITLE
wtf is this:

### ISSUE THREAD

**Issue by s0meone247** [VitorVilela7/wide-snes#43]
And yes it's broken for the entire game![image](https://user-images.githubusercontent.com/72275496/200085525-4c42da12-090b-4022-8a7e-0ed8e6ecb29c.png)

**Comment by VitorVilela7** [comment]
Looks like either the BPS patch is not applied to the ROM file or the BSO file is not together the ROM file (i.e. smw.sfc and smw.bso). Are you still having issues?

**Comment by VitorVilela7** [comment]
Please reopen this issue if you're still having difficult with setting up widescreen.
