### ISSUE TITLE
No Widescreen

### ISSUE THREAD

**Issue by okmand2** [VitorVilela7/wide-snes#44]
I Loaded The Patched File It Still Didnt Load Widescreen

**Comment by saoghalqc** [comment]
Same here, I have no idea why. 

Edit; Oh... you need to use bsnes HD-beta for it to work!

**Comment by VitorVilela7** [comment]
Have you used bsnes-hd, as @saoghalqc mentioned?

**Comment by VitorVilela7** [comment]
Please reopen this issue if you're still having difficult with setting up widescreen.
