### ISSUE TITLE
LOL Where is youtbe video ?

### ISSUE THREAD

**Issue by Usernameisalreadytaken5** [VitorVilela7/wide-snes#6]
LOL Where is youtbe video in readme ?

**Comment by ericoporto** [comment]
I am sure when he has time there will be a video, so subscribe to his channel: https://youtube.com/user/VitorSuperMarioWorld

**Comment by VitorVilela7** [comment]
There is some videos available on the internet, which I believe are enough to show off what can be done with SMW Widescreen.
