### ISSUE TITLE
Post updates under "releases"

### ISSUE THREAD

**Issue by jknut** [VitorVilela7/wide-snes#8]
If you post updates under "releases," then it will automatically notify people who are watching the releases. 

Thanks for all your work on this!!!!

**Comment by VitorVilela7** [comment]
It's a thing planned for sure. I haven't done that since I have focused on the release and hot fixes. I will add the releases as soon as possible to the correct place.

**Comment by VitorVilela7** [comment]
Done! https://github.com/VitorVilela7/wide-snes/releases
